
[[keyboard.bindings]]
action = "Hide"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "Hide"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Control"

[general]
live_config_reload = true

[[colors.indexed_colors]]
color = "#F8BD96"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#988BA2"
blue = "#96CDFB"
cyan = "#89DCEB"
green = "#ABE9B3"
magenta = "#F5C2E7"
red = "#F28FAD"
white = "#D9E0EE"
yellow = "#FAE3B0"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1D2F"

[colors.normal]
black = "#6E6C7E"
blue = "#96CDFB"
cyan = "#89DCEB"
green = "#ABE9B3"
magenta = "#F5C2E7"
red = "#F28FAD"
white = "#D9E0EE"
yellow = "#FAE3B0"

[colors.primary]
background = "#1E1D2F"
foreground = "#D9E0EE"

[cursor.style]
blinking = "on"
shape = "Block"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "transparent"
dynamic_padding = true
dynamic_title = true
opacity = 0.85
title = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 24
y = 20

[keyboard]
