#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

CONFIG_DIR="$HOME/.config/sketchybar"
ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="Hack Nerd Font:Bold:12.0"

# Icon setting
ICON_PADDING=8

# Label setting
LABEL_PADDING=16

# Background setting
BACKGROUND_PADDINGS=3
BACKGROUND_HEIGHT=20
BACKGROUND_CORNER_RADIUS=20

# BAR
bar=(
  height=26
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=4
  padding_left=2
  corner_radius=10
  y_offset=5
  margin=10
  blur_radius=10
  notch_width=0
)
sketchybar --bar "${bar[@]}"

# Default
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.highlight_color=0xffE48FA8
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Bold:12.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=20
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=10
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${defaults[@]}"

# Left
source $ITEM_DIR/left/apple.sh
# source $ITEM_DIR/left/yabai.sh
source $ITEM_DIR/left/spaces.sh

# Center
#source $ITEM_DIR/center/spotify.sh

# Right
source $ITEM_DIR/right/date_time.sh
source $ITEM_DIR/right/battery.sh
source $ITEM_DIR/right/system.sh
source $ITEM_DIR/right/wifi.sh
#source $ITEM_DIR/right/vpn.sh


# FINALIZING THE SETUP
sketchybar --update

echo "sketchybar configuration loaded..."
# add
